### ISSUE TITLE
Comentarios avance 1

### ISSUE THREAD

**Issue by AliciaMstt** [AloTerrones/ProyectoFinalBioinf2018-II#1]
Hola,

Por favor agregua un link a los datos en NCBI para que pueda revisar y estemos seguras que no tendrás problemas en utilizarlos.

Saludos,

Alicia

**Comment by AloTerrones** [comment]
En este link estan las Raw Illumina Reads 

https://www.ncbi.nlm.nih.gov/sra/?term=SRP065086

lo que no entiendo es como descargarlas, porque están muestra por muestra y no como un archivo tar o zir! 

Me puedes ayudar a descargarlas por fa?

**Comment by AliciaMstt** [comment]
Hola Alo,

Te pido que el link no lo pongas aquí, sino en tus avance1.md

Para descargar desde la línea de comando te será útil leer esto https://www.ncbi.nlm.nih.gov/books/NBK158899/
